# Generated by Django 4.1.7 on 2023-03-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('dob', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('Movie_Director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.director')),
                ('actors', models.ManyToManyField(to='api.actor')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='Dir_Movies',
            field=models.ManyToManyField(to='api.movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='Act_Movies',
            field=models.ManyToManyField(to='api.movie'),
        ),
    ]
